FROM jenkins:2.19.4

MAINTAINER vijayboopathy <vibe@initcron.org>

# Change to root user to install packages
USER root

# Install Ansible
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 && \
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y install ansible sudo && \
    echo "jenkins    ALL=NOPASSWD: ALL" >> /etc/sudoers

# Install Docker-Engine
RUN wget -qO- get.docker.io | sh && \
    usermod -aG docker jenkins

# Change to Jenkins User
USER jenkins

ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
